#!/bin/bash
# push_book
#
#   Created: 2023-08-12 (Sat)
#   Updated: 2023-08-21 (Mon)

# CHANGE THIS FOR YOU
export GITHUB_USERNAME="aimldl"
export BOOK_TITLE="genai-demo-hub"
# CHANGE THIS FOR YOU

# DO NOT CHANGE BELOW (UNLESS YOU KNOW WHAT YOU’RE DOING)
export LOCAL_BOOK="~/jupyter-book/${BOOK_TITLE}"
export LOCAL_REPO="~/github/${BOOK_TITLE}"

export OPEN_REMOTE_REPO="firefox https://github.com/${GITHUB_USERNAME}/${BOOK_TITLE}"
export OPEN_BOOK="firefox https://${GITHUB_USERNAME}.github.io/${BOOK_TITLE}"
export PUBLISH_BOOK="ghp-import -n -p -f _build/html"

function run() {
  # To display the command before running it.
  # Usage:
  #   run "COMMAND"
  # Example:
  #   If cd ${KF_DIR} is the command to run,
  #     run "cd ${KF_DIR}"
  CMD=$1
  echo $CMD
  eval $CMD
}


run "cp -r ${LOCAL_BOOK} ${LOCAL_REPO}"
run "cd ${LOCAL_REPO}"
run "git add ./*"
run "git commit -m "adding modified version of my_template!""

echo ""
run "cat ~/github/token"
echo "Copy the above token to use for the password."
echo ""

echo "After \$git push, run the following commands:"
echo "  $ ${OPEN_REMOTE_REPO}"
echo "  $ cd ${LOCAL_REPO}" 
echo "  $ ${PUBLISH_BOOK}"
echo "  $ ${OPEN_BOOK}"
echo ""

# Enter GitHub account name and paste the token
run "git push"
